/* Swig/python wrappers for tgif functions.

Similar to the auto-generated swig code generated by mupdf's scripts/wrap/.

As of 2026-05-21 we wrap:

* fz_visual_table_grid_finder()
* fz_find_visual_table_within_bounds()

*/

%{
#include "visual-table.h"

#include "mupdf/classes.h"
#include "mupdf/exceptions.h"
#include "mupdf/internal.h"


namespace mupdf
{

    /* Wrappers for fz_visual_table_grid_finder(). */
    struct fz_visual_table_grid_finder_ret
    {
        int e;
        fz_stext_grid_positions* xpos;
        fz_stext_grid_positions* ypos;
    };

    fz_visual_table_grid_finder_ret
    ll_fz_visual_table_grid_finder(fz_page* page, fz_rect* bounds)
    {
        fz_context* ctx = mupdf::internal_context_get();
        fz_visual_table_grid_finder_ret ret;
        fz_try(ctx)
        {
            ret.e = ::fz_visual_table_grid_finder(ctx, page, *bounds, &ret.xpos, &ret.ypos);
        }
        fz_catch(ctx)
        {
            internal_throw_exception(ctx);
        }
        return ret;
    }

    fz_visual_table_grid_finder_ret
    fz_visual_table_grid_finder(mupdf::FzPage& page, mupdf::FzRect& bounds)
    {
        fz_visual_table_grid_finder_ret ret = ll_fz_visual_table_grid_finder(page.m_internal, bounds.internal());
        return ret;
    }

    /* Wrappers for fz_find_visual_table_within_bounds(). */
    fz_stext_block*
    ll_fz_find_visual_table_within_bounds(fz_stext_page* stext, fz_page* page, fz_rect bounds)
    {
        fz_context* ctx = mupdf::internal_context_get();
        fz_stext_block* ret;
        fz_try(ctx)
        {
            ret = ::fz_find_visual_table_within_bounds(ctx, stext, page, bounds);
        }
        fz_catch(ctx)
        {
            internal_throw_exception(ctx);
        }
        return ret;
    }

    mupdf::FzStextBlock
    fz_find_visual_table_within_bounds(mupdf::FzStextPage& stext_page, mupdf::FzPage& page, mupdf::FzRect& bounds)
    {
        fz_stext_block* stext_block = ll_fz_find_visual_table_within_bounds(stext_page.m_internal, page.m_internal, *bounds.internal());
        return mupdf::FzStextBlock(stext_block);
    }
}

%}


namespace mupdf
{

/* Helper for fz_visual_table_grid_finder() out-params. */
struct fz_visual_table_grid_finder_ret
{
    int e;
    fz_stext_grid_positions* xpos;
    fz_stext_grid_positions* ypos;
};

/* Low-level wrapper for fz_visual_table_grid_finder(), with out-params in the
renturned struct. */
fz_visual_table_grid_finder_ret ll_fz_visual_table_grid_finder(fz_page* page, fz_rect* bounds);

/* Class-aware wrapper for fz_visual_table_grid_finder(), with out-params in
the renturned struct. Note that out-params are low-level structs, not wrapper
classes. */
fz_visual_table_grid_finder_ret fz_visual_table_grid_finder(mupdf::FzPage& page, mupdf::FzRect& bounds);

/* Low-level wrapper for fz_find_visual_table_within_bounds()s. */
fz_stext_block* ll_fz_find_visual_table_within_bounds(fz_stext_page* stext, fz_page* page, fz_rect bounds);

/* Class-aware wrapper for fz_find_visual_table_within_bounds(). */
mupdf::FzStextBlock fz_find_visual_table_within_bounds(mupdf::FzStextPage& stext_page, mupdf::FzPage& page, mupdf::FzRect& bounds);

}

%pythoncode
%{

# Convenience wrappers for fz_visual_table_grid_finder() out-params, converting
# fz_visual_table_grid_finder_ret into a returned tuple.
#
orig_ll_fz_visual_table_grid_finder = ll_fz_visual_table_grid_finder

def ll_fz_visual_table_grid_finder(page, bounds):
    '''
    Returns e, xpos, ypos.
    '''
    ret = orig_ll_fz_visual_table_grid_finder(page, bounds)
    return ret.e, ret.xpos, ret.ypos

orig_fz_visual_table_grid_finder = fz_visual_table_grid_finder

import pymupdf

def fz_visual_table_grid_finder(page, bounds):
    '''
    Returns e, xpos, ypos.
    '''
    ret = orig_fz_visual_table_grid_finder(page, bounds)
    return ret.e, pymupdf.mupdf.FzStextGridPositions(ret.xpos), pymupdf.mupdf.FzStextGridPositions(ret.ypos)

%}
